theme: jekyll-theme-minimal

title: ARTSEY.io
description: ARTSEY.io: An Easy, Fast, Open One-Handed Keyboard System
  
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - contact.md
  - zmk.md
  - qmk.md