theme: jekyll-theme-minimal
  
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - design.md


title: "ARTSEY"
description: "An Easy, Fast, Open One-Handed Keyboard System"
logo: logo.png
